docs/src/examples.md

Fix a few mistakes in the examples section of the docs.

Documentation fixes

---

src/Schedulers.jl

This change to the `epmapreduce!` doc string hopefully makes it clearer that the scratch space must be accessible from all workers in the cluster.

add missing documentation for epmapreduce!

---

Project.toml
docs/src/examples.md
src/Schedulers.jl
test/runtests.jl

Generalize from arrays, to any type, and allow customization of the reducer method.

generalize what can be reduced

---

src/Schedulers.jl

if addprocs fails in the elastic loop, then show the error

---

src/Schedulers.jl

When the worker Julia process exits (e.g. due to a seg-fault), we
want to ensure that the Distributed.kill method is called.

Improve error handling

---

src/Schedulers.jl
test/runtests.jl

Allow for minworkers and maxworkers to be set via a function.  This
should allow for the bounds on the number of workers to change during
the course of the parallel map.  For example, the value could update
due to a change in a file, database or some closed-over variable.

Interactive cluster sizing

---

src/Schedulers.jl

small change to ensure that errors are properly logged.

improve error handling for map-reduce

---

src/Schedulers.jl
test/runtests.jl

fix bug where initialization will run more than once due to a race between the async initialization, and the elastic loop.

initialization bugfix

---

src/Schedulers.jl
test/runtests.jl

The focus here is the parallel map rather than the parallel map reduce method.

add callback option for custom journaling behavior

---

src/Schedulers.jl

the `handle_exception` method called on line 801 pops the pid from the `checkpoints` dictionary, and pushes it onto the `orphans` dictionary.  This, in turn, resulted in an error when trying to get `checkpoints[pid]`.

fix pmapreduce fault tolerance bug

---

docs/src/examples.md
src/Schedulers.jl
test/runtests.jl

fetch the Future, so that the user of epmapreduce doesn't need to

auto-fetch

---

docs/src/examples.md
src/Schedulers.jl
test/runtests.jl

This changes the API so that options controlling the behavior of the `epmap` and `epmapreduce!` are passed via a `SchedulerOptions` struct.  The reason for the change is so that typos in parameters are caught by Julia.  Previously, those typos would have resulted in the parameters being passed on to the function being mapped over, often resulting in confusing errors and/or behavior.
For example:
```julia
epmap(foo, 1:10; epmap_maxworkers=5)
```
becomes
```julia
epmap(SchedulerOptions(maxworkers=5), foo, 1:10)
```
and
```julia
epmapreduce!(result, foo, 1:10; epmap_maxworkers=5)
```
becomes
```julia
epmapreduce!(result, SchedulerOptions(maxworkers=5), foo, 1:10)
```
Unfortunately, this is a breaking change.

breaking API change

---

src/Schedulers.jl

The elastic loop needs to be active while the map and reduce loops are running.  If the elastic loop exits early, then the reduce/map loops may hang due to the communication via channels between the reduce and elastic loop, and between the map and elastic loop.

Fix race condition

---

src/Schedulers.jl
test/runtests.jl

This allows us to create partial reductions.  The partial reduction is triggered using a user-defined method.  This allows us to save partial results before all items being mapped over are complete.  This can be an important quality control step when mapping over a very large set of tasks.  In order to define these partial reductions, we allow the user to provide two methods:
1. `reduce_trigger(eloop)`.  With this method, the user can define when (or under what conditions) a reduction is triggered.  For example consider the following code:
```julia
function my_reduce_trigger(eloop, tic)
if time() - tic[] > 600
trigger_reduction!(eloop)
tic[] = time()
end
end
tic = Ref(time())
options = SchedulerOptions(;reduce_trigger=eloop->my_reduce_trigger(eloop, tic), ...)
```
If `options` is used in …

partial reductions feature

---

src/Schedulers.jl

this puts less onus on the user to ensure that the method being mapped over returns `nothing`.

switch from fetch to wait in some cases

---

src/Schedulers.jl

especially with respect to the reduction.

Improve debug logging

---

src/Schedulers.jl

if storage hangs, we still want to complete.

add a time-out for file deletion

---

src/Schedulers.jl

fix bug in computing the number of machines to add.

book-keeping error

---

src/Schedulers.jl

Improve logic for removing machines at the end of the elastic loop.

Improve clean-up logic

---

src/Schedulers.jl

see https://github.com/ChevronETC/AzManagers.jl/pull/140

Defaultthreadpool

---

src/Schedulers.jl
test/runtests.jl

Allow for user specfied task specific checkpoint and restart methods. The checkpoint method is called when a machine is being preempted, and a restart method is called when starting a task.  In this way, one can checkpoint and restart from a partially complete task.

Preempt actions

---

src/Schedulers.jl
test/runtests.jl

added the late termination feature, and updated the unit tests.

Fwinew2skip
